### ISSUE TITLE
Nested list support

### ISSUE THREAD

**Issue by satvikpendem** [alexfedoseev/re-dnd#11]
Is there a way to have lists within lists, for example in a nested list hierarchy like so?

```
- A
    - A1
        -A1a
        -A1b
    -A2
-B
```

**Comment by alex35mil** [comment]
@satvikpendem It should be possible, yeah. Check out https://re-dnd.now.sh/#nested-vertical-lists

**Comment by alex35mil** [comment]
Though there is a better way to achieve it. I need to sync up current version of `re-dnd` that's used at [minima.app](https://minima.app/) with this repo. I will look into it next week.

**Comment by alex35mil** [comment]
See #14 . Let me know if you have any further questions.
