### ISSUE TITLE
API for `isDragging` other than className

### ISSUE THREAD

**Issue by kgoggin** [alexfedoseev/re-dnd#16]
Just started using this lib and it was so easy to get up and running - thanks so much!

I was wondering what you thought of adding a way to know when the `Items.DraggableItem` component was in the midst of being dragged, other than just when specifying the `className` prop. My use case is that my app uses React Native Web, so the styling API isn't based on class names. I can think of a few escape hatches I could use, but it'd be great if the library supported tracking that state change somehow.

Not sure if it'd make more sense to add another variant for the component's `children` that was a render function that contained the state, or possibly it'd make more sense to have another handler at the `DndManager` level that fired whenever an item started being dragged so you could do a more global state update if you needed? I'm sure you've got a better handle on what would be best performance-wise!

Thanks!

**Comment by alex35mil** [comment]
Hey, you're 100% right that current interface misses a lot of handlers and I'm up for adding those. Let me know which ones you need for your use cases and I'll happily add them to the `DndManager` api.

I'm not familiar with React Native Web, would those handlers solve your use cases or it would require something else (can you elaborate more on the cases if that's the case)?

**Comment by kgoggin** [comment]
My use case is that I need a way to update the state of the child of a `DraggableItem`:

 1. When it starts being dragged
 2. When it stops being dragged

Specifically, I want to update its styling and since RNW's styling's API doesn't use CSS classes, the existing `className` API won't work for me.

So, I think a `onDragStart` handler would allow me to add a case to my global state reducer and track the currently dragged item. I'd also need a handler that was called when an item stops being dragged but returns to the original location (because `onReorder` wouldn't get called). 

That's probably a better solution than adding that API to `DraggableItem` somehow because it'd allow for you to update things other than just the item being dragged while the user was in the middle of dragging something!

**Comment by alex35mil** [comment]
Gotcha, makes sense! I will add these handlers to the `DndManager` interface and ping you in this issue 👍

**Comment by alex35mil** [comment]
@kgoggin Can you check #17? If it's enough to handle your case, I will cut the release.

**Comment by kgoggin** [comment]
Left a comment on it - thanks so much for adding this!
