### ISSUE TITLE
Consider moving Webapi to peer dependency

### ISSUE THREAD

**Issue by TomiS** [alexfedoseev/re-dnd#21]
Not in any way a critical issue, just something to think about...

I'd argue Webapi is almost as common as reason-react as a dependency. So when most people have it installed anyway, it will cause awkward "Duplicated package" warning that could be avoided just by defining it as a peer dependency.

**Comment by TomiS** [comment]
Ouch, I think I was actually having a duplicate dependency because of how yarn resolved bs-webapi dependency. So maybe this issue is invalid after all.

**Comment by TomiS** [comment]
I realize I'm being a bit inconsistent here, but after a while I think this is a problem after all.

I tried updating my root level dependecy of `bs-webapi` to 0.18.0 but because I'm also using this library, I'm now getting duplicate dependency for bs-webapi because this lib requires exactly 0.15.9.

I don't know which one would be better, to make this a peer dependency or change the version requirement to something like `>=0.15.9` (which is maybe too loose, Idk, there are some backwards compatibility breaks in webapi). But in any case, having a very strict version requirement like now basically makes it impossible to use this lib in the long run without forking.

**Comment by ClaireNeveu** [comment]
@TomiS Could you publish a version with this fix in place? Re-DnD doesn't work with the latest version of bucklescript because it pins an old version of bs-webapi.

**Comment by TomiS** [comment]
@ClaireNeveu Hi. As I'm not the author/maintainer of this repo, you might want to direct your question to @alexfedoseev .

**Comment by ClaireNeveu** [comment]
Ah, my apologies

**Comment by alex35mil** [comment]
Sorry for delay, 3.0.0 is on npm.
