### ISSUE TITLE
Replace bs-webapi with rescript-webapi?

### ISSUE THREAD

**Issue by SamWoolerton** [alexfedoseev/re-dnd#26]
Looks like bs-webapi hasn't been touched in a year, whereas [rescript-webapi](https://github.com/tinymce/rescript-webapi) is under active development (I'm not affiliated with either). If the bindings are the same but just updated, then might be good to update this.

Would also be great to add a note to Readme to go install that package too (not sure if it's obvious for others but I'm new to Rescript and was a bit surprised).

**Comment by alex35mil** [comment]
Thanks for bringing this up! Yeah, we should probably do it. I will check out `rescript-webapi` sometime.

**Comment by darenju** [comment]
> Would also be great to add a note to Readme to go install that package too (not sure if it's obvious for others but I'm new to Rescript and was a bit surprised).

Bumping this. Needed to re-`build -with-deps` to notice I had to install `bs-webapi` and add it in `bs-dependencies` :)

**Comment by alex35mil** [comment]
Fixed in #31.
