### ISSUE TITLE
Do another release

### ISSUE THREAD

**Issue by shulhi** [alexfedoseev/re-dnd#27]
We are upgrading all of our packages to use rescript (moving from reason) and seems like res-logger doesn't work. Looking at master, this has been changed to rescript-logger but the npm package hasn't been updated to reflect this.

Can you please do another release. Thank you.

**Comment by alex35mil** [comment]
I need to convert this package to ReScript. Will look into it this or next week.

**Comment by alex35mil** [comment]
`rescript-dnd` is on npm.
